### PR TITLE
Upgrade setuptools on Python from system

### PR DESCRIPTION
**Pull request by humitos**
We were upgrading `pip` but it's also a good idea to upgrade `setuptools` as well.

Related to https://github.com/rtfd/readthedocs.org/issues/5572

### CODE REVIEW

**Comment by webknjaz** [comment]
It makes sense to link https://github.com/pypa/pip/issues/6264 in the commit message as well. That issue is happening because pip somehow fails to properly isolate build env in PEP 517 mode.

**Comment by humitos** [comment]
@webknjaz thanks! I adapted your message and included it on the commit.

**Comment by webknjaz** [comment]
Thanks, I'll try to verify this locally now.

**Comment by webknjaz** [comment]
Oh, by the way, now that setuptools has version 41 released it's also needed to bump it in this command
```console
/home/docs/checkouts/readthedocs.org/user_builds/octomachinery/envs/latest/bin/python -m pip install --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/octomachinery/.cache/pip Pygments==2.3.1 setuptools<41 docutils==0.14 mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<0.6
```

**Comment by webknjaz** [comment]
Anyway, it seems to be working now.

**Comment by webknjaz** [comment]
Is this going to be available in production anytime soon?

**Comment by humitos** [comment]
@webknjaz I'm not sure.

I'd like to do it by the end of the month if I have time.

**Pull request merged**
