### PR TITLE
use the latest version of miniconda

### PR DESCRIPTION
**Pull request by wkerzendorf**
this will likely fix bugs that appear from older versions of conda and is in relation to issue rtfd/readthedocs.org#3150

### CODE REVIEW

**Comment by ericholscher** [comment]
I think it would be best to have this be pinned to a specific version. I don't want it to update every time we run Docker, as that could leave us with random versions that are broken.

**Comment by wkerzendorf** [comment]
@ericholscher is that good?

**Comment by wkerzendorf** [comment]
@ericholscher is there anything specific that would help this get merged. We're very eager to use the new conda with our documentation (otherwise it doesn't build). If there is anything we can do to speed things up (help, unfortunately not money as we're from academia and are poor :wink: )

**Comment by agjohnson** [comment]
@wkerzendorf thanks for the PR! I was just going to make this change myself. This PR looks fine, would you also like to backport this to the releases/2.x branch?

**Comment by wkerzendorf** [comment]
@agjohnson let me know if I can help with backport

**Comment by agjohnson** [comment]
@wkerzendorf feel free to apply on a separate PR against `releases/2.x`, I can get this PR merged now though.

**Comment by wkerzendorf** [comment]
@agjohnson does that mean - it will work now?

**Comment by wkerzendorf** [comment]
@agjohnson and its now not linked to the latest. Should we pin it to latest?

**Comment by agjohnson** [comment]
No, we rather pin to explicit versions to remove any surprises. We do this across all of our dependencies to reduce operations load.

**Comment by agjohnson** [comment]
Oh and no, image won't work immediately. It takes hours to build and I likely won't install until later tonight or tomorrow.

**Comment by wkerzendorf** [comment]
@agjohnson unfortunately it still isn't installed - any ETA?

**Comment by agjohnson** [comment]
Didn't get to it today, this will be on my list next week. We avoid ops changes on weekends.

**Pull request merged**
