### PR TITLE
Add auxlib for conda

### PR DESCRIPTION
**Pull request by sternb0t**
Greetings, not sure if you take pull requests, but I had to add this `auxlib` install in order to build the docker images on a relatively fresh Ubuntu 14.04 machine. It seems `conda` requires it: https://github.com/conda/conda/issues/2182. Thanks!

### CODE REVIEW

**Comment by richbodo** [comment]
Yup, I needed to add "pip install auxlib" prior to the conda install line as well.

**Comment by sternb0t** [comment]
Thanks for the 2nd, @richbodo

**Comment by agjohnson** [comment]
Thanks for the addition! Any reason this isn't required for python3? Also, this could be reduced to a single line on the previous call to `pip2`.

**Comment by sternb0t** [comment]
I actually haven't tested with python3, but I suppose it won't hurt to have both. Up to you!

**Comment by agjohnson** [comment]
I haven't run into issues with either version requiring `auxlib`, but `auxlib` does seem to support python3, so may as well.

**Comment by sternb0t** [comment]
Cool, added that. Thanks!

**Comment by agjohnson** [comment]
Great, thanks for the update! There will likely be some delay before it hits RTD.org, we have a heavy operations load these next two weeks.

**Comment by sternb0t** [comment]
Cool, thank you!

**Pull request merged**
