### PR TITLE
Add conda-forge channel to the 2.x build image

### PR DESCRIPTION
**Pull request by humitos**
Closes https://github.com/rtfd/readthedocs.org/issues/2713

If this is something we want, I will make another PR to do the same in the `latest` build image.

We need some testing for this, also.

### CODE REVIEW

**Comment by humitos** [comment]
On the other hand, I'm thinking if this is something that we want to do in the image or as a build command every time a RTD project builds.

**Comment by willingc** [comment]
@humitos Here's a link to the docker-stacks that we use in Jupyter and how we handle conda and conda-forge channel https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L66

**Comment by humitos** [comment]
@willingc great!

The only difference that I see is the `--system` that in RTD specific case I think won't change too much since the all the commands inside the docker image are ran by the `docs` user, but anyway I think we should use it :)

**Comment by ericholscher** [comment]
+1 Thanks @willingc -- Looks like we should steal the no auto upgrade bit too?

**Comment by humitos** [comment]
@ericholscher if we _really want_ to have a pinned version, we should... otherwise it will upgrade on every `conda env create`

**Comment by willingc** [comment]
I would seriously consider https://github.com/rtfd/readthedocs.org/issues/2566#issuecomment-285160979 from @sylvaincorlay.

**Comment by ericholscher** [comment]
@humitos This should be targeting the `release-2.x` branch, I believe. I've gone ahead and updated it.

**Comment by ericholscher** [comment]
Gonna call this done, and merge it. We can track removing our version overrides for conda separately.

**Pull request merged**
