### PR TITLE
Change build matrix to build the docker images

### PR DESCRIPTION
**Pull request by browniebroke**
I'm not sure whether this has been attempted before, but it looks like something that could help verify that nothing major break when things get added.

### CODE REVIEW

**Comment by browniebroke** [comment]
Apart from the fact that things don't pass now, the build time increases a lot with this being added. I think this means the images will be built twice to be released with the current setup: on Travis and on Dockerhub... Leading to long wait times for maintainers!

To add this, I think that'll require deploying to Dockerhub from Travis, as explained here:

https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

**Comment by humitos** [comment]
I don't really know how is our process of releasing the docker images and pulling them from the servers. I never did it. Pinging @agjohnson so he can take a look at this PR and decide what path to take here.

**Comment by bebehei** [comment]
With the latest overhaul of dockerhub, it's possible to set commit statuses, too. So dockerhub can build a commit and will report your commit status (the green checkmark or the red cross) to your commit.

I'm not sure, if it works for PRs, but the [autotest docs](https://docs.docker.com/docker-hub/builds/automated-testing/#enable-automated-tests-on-a-repository) mention "building PRs".

As dockerhub is more proficient in building docker images, I'd change over to dockerhub.

**Comment by browniebroke** [comment]
I haven't heard about that, but it looks very promising! Thanks for sharing 🎉

**Comment by browniebroke** [comment]
I'm going to close this, I took a look at the Docker Hub build and it looks like it doesn't require any code change. It seems more secure as well.

**Pull request closed without merging**
