### PR TITLE
Set default locale to C.UTF-8

### PR DESCRIPTION
**Pull request by berkerpeksag**
This should fix issues like https://github.com/rtfd/readthedocs.org/issues/2225
and https://github.com/rtfd/readthedocs.org/issues/2101

### CODE REVIEW

**Comment by astrofrog** [comment]
@berkerpeksag - I *just* ran into this issue and was about to report it. Once this is merged, how long will this take to propagate to the production build system? (just to know whether I should try and implement a workaround)

**Comment by agjohnson** [comment]
@astrofrog Likely next week. We avoid deploys going into the weekend, and I'm the only one on call.

**Comment by agjohnson** [comment]
@astrofrog though I am happy to put a project on the 16.04 beta image and get that image out today. That will just take a few hours for the image to build

@berkerpeksag I assume we need the same change in the 16.04 image

**Comment by berkerpeksag** [comment]
@agjohnson good point, apparently I misread `16.04/Dockerfile`. Done, thanks!

**Comment by astrofrog** [comment]
@agjohnson - next week is fine, thanks!

**Comment by agjohnson** [comment]
Roger. I put this on our list for next week deploy.

**Pull request merged**
